[features]
seeds = false
[programs.localnet]
backend = "86rqd8wDoqWCvyYuFsZYq7o7mQLUrBwMD9qUTynkWy1r"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/ricardo/.config/solana/id.json"

[scripts]
test = "pnpm exec mocha -t 1000000 tests/"
